/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const FetchOptions: typeof import('@vue-api/core')['FetchOptions']
  const Field: typeof import('@vue-api/core')['Field']
  const IHttpModel: typeof import('@vue-api/core')['IHttpModel']
  const IRequestOptions: typeof import('@vue-api/core')['IRequestOptions']
  const useApiAuth: typeof import('./api/_composables_/index')['useApiAuth']
  const useApiCmsBlogsArticle: typeof import('./api/_composables_/index')['useApiCmsBlogsArticle']
  const useApiCmsBlogsIndex: typeof import('./api/_composables_/index')['useApiCmsBlogsIndex']
  const useApiUsers: typeof import('./api/_composables_/index')['useApiUsers']
  const useAuth: typeof import('./api/_composables_/index')['useAuth']
  const useCmsBlogsArticle: typeof import('./api/_composables_/index')['useCmsBlogsArticle']
  const useCmsBlogsIndex: typeof import('./api/_composables_/index')['useCmsBlogsIndex']
  const useOfetchModel: typeof import('@vue-api/core')['useOfetchModel']
  const useTransform: typeof import('@vue-api/core')['useTransform']
  const useUsers: typeof import('./api/_composables_/index')['useUsers']
}
