/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const useApiAuth: typeof import('./api/_composables_/index')['useApiAuth']
  const useApiCmsBlogsArticle: typeof import('./api/_composables_/index')['useApiCmsBlogsArticle']
  const useApiCmsBlogsIndex: typeof import('./api/_composables_/index')['useApiCmsBlogsIndex']
  const useApiUsers: typeof import('./api/_composables_/index')['useApiUsers']
  const useAuth: typeof import('./api/_composables_/index')['useAuth']
  const useCmsBlogsArticle: typeof import('./api/_composables_/index')['useCmsBlogsArticle']
  const useCmsBlogsIndex: typeof import('./api/_composables_/index')['useCmsBlogsIndex']
  const useUsers: typeof import('./api/_composables_/index')['useUsers']
}
